# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Morphia Reproducers

on: [ push, pull_request, workflow_dispatch ]

jobs:
  Morphia:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 11, 17 ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: 'maven'
      - name: Compile Code
        run: mvn install
        env:
          MONGODB: 5.0.0
